## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW1_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import pandas as pd
import numpy as np

#1-1
frame = pd.DataFrame(data)
print(frame)

#1-2
frame[(((frame["job"]) == "psychologist") | ((frame["job"]) == "teacher")) & (frame["num_cars"]> frame["family_size"])]

#1-3
frame[(frame["family_size"] <= 2) & (frame["num_cars"] >= 1)]

#1-4
uniqueJobs = np.unique(frame["job"])
print(len(uniqueJobs))

     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
4


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
weights.groupby(fruit).mean()




apple     6.500000
banana    4.666667
carrot    5.600000
dtype: float64

**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
# 3-1

sorted = np.argsort(course_name)
print(sorted)

# 3-2

startsWithP = np.char.startswith(course_name, "P")
print(startsWithP)




[1 3 0 2 4]
[ True False False  True False]


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
# 4-1
print("Original:", student_id)
print("Reversed:", np.flip(student_id, 0))

# 4-2
arr = np.sort(student_id)
# picks largest 3 from sorted array
print(arr[-3:])


Original: [1023 5202 6230 1671 1682 5241 4532]
Reversed: [4532 5241 1682 1671 6230 5202 1023]
[5202 5241 6230]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
# 0 is included as it is a multiple of every number
arr = np.arange(100)
multiples_arr = np.where((arr % 3 == 0) | (arr % 5 == 0))
print(np.sum(multiples_arr))

2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# 6-1
arr[:, [1,2]] = arr[:, [2,1]]
print(arr)

# 6-2
arr[[0,1], :] = arr[[1,0], :]
print(arr)
